name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - '[0-9]+.[0-9]{2}'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - debian-bullseye
          - debian-bookworm
          - debian-trixie
          - ubuntu-focal
          - ubuntu-jammy
          - ubuntu-noble
          - ubuntu-oracular
          - ubuntu-plucky
          - fedora-41
          - fedora-42
          - centos-9
          - centos-10
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        run: |
          make ${{ matrix.target }}
