name: ci

# Default to 'contents: read', which grants actions to read commits.
#
# If any permission is set, any permission not included in the list is
# implicitly set to "none".
#
# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - '[0-9]+.[0-9]{2}'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60 # guardrails timeout for the whole job
    strategy:
      fail-fast: false
      matrix:
        target:
          - debian-bullseye
          - debian-bookworm
          - ubuntu-focal
          - ubuntu-jammy
          - ubuntu-noble
          - ubuntu-oracular
          - fedora-41
          - fedora-42
          - centos-9
          - centos-10
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        run: |
          make ${{ matrix.target }}
